### ISSUE TITLE
Executable not statically linked

### ISSUE THREAD

**Issue by char101** [SeppPenner/PgBouncerWinBinaries#1]
Hi,

Just want to drop a note letting you know that your compiled pgbouncer.exe is not statically linked with msys libraries, so the user using it will not be able to run it unless he has msys installed. That's also why the saito version is 500KB larger.

saito pgbouncer.exe
```
Dump of file pgbouncer.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    ADVAPI32.dll
    KERNEL32.dll
    msvcrt.dll
    SHELL32.dll
    USER32.dll
    WS2_32.dll
```

this repository pgbouncer.exe
```
Dump of file pgbouncer_1.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    msys-crypto-1.1.dll
    msys-event-2-1-7.dll
    msys-2.0.dll
    msys-ssl-1.1.dll
    KERNEL32.dll
    WS2_32.dll
```

**Comment by SeppPenner** [comment]
Yes, this is a big problem. I'm still not really able to clean build this on Windows. If you have any suggestions, please let me know (I'm not a C expert as well...) 😅

**Comment by char101** [comment]
Usually you only need to `export CFLAGS='-static'` when building pgbouncer and its dependencies (libevent & openssl).

**Comment by SeppPenner** [comment]
Well, I had some bigger issues with the build process already. I will see if I can get this to work properly.

**Comment by SeppPenner** [comment]
If you want to provide a build and / or build instructions, please feel free to do so. I'm just not using pgbouncer anymore and thus will not investigate the issue any further...
