### ISSUE TITLE
Pandoc fix

### ISSUE THREAD

**Issue by Srikanth-ki** [SeppPenner/PgBouncerWinBinaries#2]
Hey just copy the Pandoc.exe to system32 folder it will do the job. 

If you type "which Pandoc" it will show the path where its looking for the exe file.... It solved the problem hope it helps.

**Comment by SeppPenner** [comment]
Thank you, this might be useful for others who are interested in pgbouncer binaries :) I'm not actively using it anymore and therefore haven't followed anything related in the last years... I will close this issue, but I will take PRs if anyone wants to put binaries for a later version.
